name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: docker compose build

      - name: Start Services
        run: docker compose up -d

      - name: Run Mypy
        run: docker compose exec demo-app uv run mypy api/

      - name: Run Ruff
        run: docker compose exec demo-app uv run ruff check

      - name: Run Tests
        run: docker compose exec demo-app uv run pytest

      - name: Tear Down Services
        run: docker compose down
